/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedCompararRouteImport } from './routes/_authenticated/comparar'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNovaRouteImport } from './routes/_authenticated/nova'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedCotacoesIndexRouteImport } from './routes/_authenticated/cotacoes.index'
import { Route as AuthenticatedCotacoesIdRouteImport } from './routes/_authenticated/cotacoes.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompararRoute = AuthenticatedCompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaRoute = AuthenticatedNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotacoesIndexRoute =
  AuthenticatedCotacoesIndexRouteImport.update({
    id: '/cotacoes/',
    path: '/cotacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCotacoesIdRoute = AuthenticatedCotacoesIdRouteImport.update({
  id: '/cotacoes/$id',
  path: '/cotacoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/cotacoes/$id': typeof AuthenticatedCotacoesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/cotacoes/$id': typeof AuthenticatedCotacoesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/cotacoes': typeof AuthenticatedCotacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/comparar': typeof AuthenticatedCompararRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/nova': typeof AuthenticatedNovaRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/cotacoes/$id': typeof AuthenticatedCotacoesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/comparar'
    | '/fornecedores'
    | '/inicio'
    | '/nova'
    | '/oportunidades'
    | '/produtos'
    | '/cotacoes/$id'
    | '/api/public/health'
    | '/cotacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/comparar'
    | '/fornecedores'
    | '/inicio'
    | '/nova'
    | '/oportunidades'
    | '/produtos'
    | '/cotacoes/$id'
    | '/api/public/health'
    | '/cotacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/busca'
    | '/_authenticated/comparar'
    | '/_authenticated/fornecedores'
    | '/_authenticated/inicio'
    | '/_authenticated/nova'
    | '/_authenticated/oportunidades'
    | '/_authenticated/produtos'
    | '/_authenticated/cotacoes/$id'
    | '/api/public/health'
    | '/_authenticated/cotacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparar': {
      id: '/_authenticated/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof AuthenticatedCompararRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova': {
      id: '/_authenticated/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AuthenticatedNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes/': {
      id: '/_authenticated/cotacoes/'
      path: '/cotacoes'
      fullPath: '/cotacoes/'
      preLoaderRoute: typeof AuthenticatedCotacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes/$id': {
      id: '/_authenticated/cotacoes/$id'
      path: '/cotacoes/$id'
      fullPath: '/cotacoes/$id'
      preLoaderRoute: typeof AuthenticatedCotacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedCompararRoute: typeof AuthenticatedCompararRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNovaRoute: typeof AuthenticatedNovaRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedCotacoesIdRoute: typeof AuthenticatedCotacoesIdRoute
  AuthenticatedCotacoesIndexRoute: typeof AuthenticatedCotacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedCompararRoute: AuthenticatedCompararRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNovaRoute: AuthenticatedNovaRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedCotacoesIdRoute: AuthenticatedCotacoesIdRoute,
  AuthenticatedCotacoesIndexRoute: AuthenticatedCotacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
