/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCompararRouteImport } from './routes/_authenticated/comparar'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNovaRouteImport } from './routes/_authenticated/nova'
import { Route as AuthenticatedCotacoesIndexRouteImport } from './routes/_authenticated/cotacoes.index'
import { Route as AuthenticatedCotacoesIdRouteImport } from './routes/_authenticated/cotacoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompararRoute = AuthenticatedCompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaRoute = AuthenticatedNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotacoesIndexRoute =
  AuthenticatedCotacoesIndexRouteImport.update({
    id: '/cotacoes/',
    path: '/cotacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCotacoesIdRoute = AuthenticatedCotacoesIdRouteImport.update({
  id: '/cotacoes/$id',
  path: '/cotacoes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/cotacoes/$id': typeof AuthenticatedCotacoesIdRoute
  '/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/cotacoes/$id': typeof AuthenticatedCotacoesIdRoute
  '/cotacoes': typeof AuthenticatedCotacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/comparar': typeof AuthenticatedCompararRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/nova': typeof AuthenticatedNovaRoute
  '/_authenticated/cotacoes/$id': typeof AuthenticatedCotacoesIdRoute
  '/_authenticated/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comparar'
    | '/inicio'
    | '/nova'
    | '/cotacoes/$id'
    | '/cotacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comparar'
    | '/inicio'
    | '/nova'
    | '/cotacoes/$id'
    | '/cotacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/comparar'
    | '/_authenticated/inicio'
    | '/_authenticated/nova'
    | '/_authenticated/cotacoes/$id'
    | '/_authenticated/cotacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comparar': {
      id: '/_authenticated/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof AuthenticatedCompararRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova': {
      id: '/_authenticated/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AuthenticatedNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes/': {
      id: '/_authenticated/cotacoes/'
      path: '/cotacoes'
      fullPath: '/cotacoes/'
      preLoaderRoute: typeof AuthenticatedCotacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes/$id': {
      id: '/_authenticated/cotacoes/$id'
      path: '/cotacoes/$id'
      fullPath: '/cotacoes/$id'
      preLoaderRoute: typeof AuthenticatedCotacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompararRoute: typeof AuthenticatedCompararRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNovaRoute: typeof AuthenticatedNovaRoute
  AuthenticatedCotacoesIdRoute: typeof AuthenticatedCotacoesIdRoute
  AuthenticatedCotacoesIndexRoute: typeof AuthenticatedCotacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompararRoute: AuthenticatedCompararRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNovaRoute: AuthenticatedNovaRoute,
  AuthenticatedCotacoesIdRoute: AuthenticatedCotacoesIdRoute,
  AuthenticatedCotacoesIndexRoute: AuthenticatedCotacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
